# Generated by Django 5.2.10 on 2026-01-17 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_number', models.CharField(blank=True, max_length=50, null=True)),
                ('power_only', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('covered', 'Covered'), ('dispatched', 'Dispatched'), ('enroute', 'Enroute'), ('reserved', 'Reserved'), ('rest', 'Rest'), ('stop', 'Stop'), ('home', 'Home')], default='ready', max_length=20)),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_state', models.CharField(max_length=50)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_state', models.CharField(max_length=50)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_dispatcher', models.ForeignKey(limit_choices_to={'role': 'dispatch'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_trucks', to=settings.AUTH_USER_MODEL)),
                ('primary_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_assignments', to='drivers.driver')),
                ('secondary_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_assignments', to='drivers.driver')),
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_board', to='fleet.truck')),
            ],
        ),
    ]
