# Generated by Django 5.2.10 on 2026-01-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchboard',
            old_name='eta',
            new_name='eta_datetime',
        ),
        migrations.AddField(
            model_name='dispatchboard',
            name='eta_type',
            field=models.CharField(choices=[('PU', 'Pickup'), ('DEL', 'Delivery')], default='DEL', max_length=3),
        ),
    ]
