# Generated by Django 5.2.10 on 2026-01-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_rename_eta_dispatchboard_eta_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchboard',
            name='destination_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchboard',
            name='destination_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchboard',
            name='eta_type',
            field=models.CharField(blank=True, choices=[('PU', 'Pickup'), ('DEL', 'Delivery')], max_length=3, null=True),
        ),
    ]
