# Generated by Django 5.2.10 on 2026-01-16 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('cdl_photo', models.ImageField(blank=True, null=True, upload_to='drivers/cdl/')),
                ('cdl_expiration_date', models.DateField()),
                ('hire_date', models.DateField()),
                ('home_city', models.CharField(max_length=100)),
                ('home_state', models.CharField(max_length=50)),
                ('experience_years', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('vacation', 'Vacation'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='fleet.truck')),
            ],
        ),
    ]
