# Generated by Django 5.2.10 on 2026-01-16 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_number', models.CharField(max_length=50, unique=True)),
                ('plate_number', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=50, unique=True)),
                ('year', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trucks/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_truck', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
