# Generated by Django 5.2.10 on 2026-01-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Watan Logistics Inc', max_length=255)),
                ('mc_number', models.CharField(default='1660350', max_length=50)),
                ('usdot_number', models.CharField(default='4274064', max_length=50)),
                ('address', models.CharField(default='81 Colonial Hills Dr, Akron, OH 44310', max_length=255)),
                ('phone', models.CharField(default='(216) 202-5556', max_length=50)),
                ('email', models.CharField(default='info@watanlogisticsinc.com', max_length=100)),
            ],
        ),
    ]
