# Generated by Django 5.2.10 on 2026-01-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadhistory',
            name='bill_of_lading',
            field=models.FileField(blank=True, null=True, upload_to='bols/'),
        ),
        migrations.AddField(
            model_name='loadhistory',
            name='rate_confirmation',
            field=models.FileField(blank=True, null=True, upload_to='rate_confirmations/'),
        ),
    ]
