# Generated by Django 5.2.10 on 2026-01-22 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_history', '0002_loadhistory_bill_of_lading_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadhistory',
            name='dispatcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads_as_dispatcher', to=settings.AUTH_USER_MODEL),
        ),
    ]
