# Generated by Django 5.2.10 on 2026-01-22 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('load_history', '0003_alter_loadhistory_dispatcher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loadhistory',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='fleet.truck'),
        ),
        migrations.AlterField(
            model_name='loadhistory',
            name='dispatcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loads', to=settings.AUTH_USER_MODEL),
        ),
    ]
